%% lowpass filter N=20
clc, clear all, close all;
N=20;
n=-N:1:N;
w=pi/4;
h=w/pi*sinc(w/pi*n);
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('ideal lowpass filter for N=20');
subplot(212);
plot(n,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('ideal lowpass filter for N=20');
%% lowpass filter N=40
clc, clear all, close all;
N=40;
n=-N:1:N;
w=pi/4;
h=w/pi*sinc(w/pi*n);
x=-pi:N:pi;
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('ideal lowpass filter for N=40');
subplot(212);
plot(x,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('Ideal lowpass filter for N=40');
%% highpass filter N=20
clc, clear all, close all;
N=20;
n=-N:1:N;
w=pi/4;
imp=[zeros(1,N),1,zeros(1,N)];
h=imp(n+N+1)-w/pi*sinc(w/pi*n);
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Ideal highpass filter for N=20');
subplot(212);
plot(n,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('Ideal highpass filter for N=20');
%% highpass filter N=40
clc, clear all, close all;
N=40;
n=-N:1:N;
w=pi/4;
imp=[zeros(1,N),1,zeros(1,N)];
h=imp(n+N+1)-w/pi*sinc(w/pi*n);
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Ideal highpass filter for N=20');
subplot(212);
plot(n,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('Ideal highpass filter for N=20');
%% bandpass filter N=20
clc, clear all, close all;
N=20;
n=-N:1:N;
w=pi/4;
a=pi/3;
h=cos(a*n)*w/pi.*sinc(w/pi*n);
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Ideal bandpass filter for N=20');
subplot(212);
plot(n,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('Ideal bandpass filter for N=20');
%% bandpass filter N=40
clc, clear all, close all;
N=40;
n=-N:1:N;
w=pi/4;
a=pi/3;
h=cos(a*n)*w/pi.*sinc(w/pi*n);
figure;
subplot(211);
stem(n,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Ideal bandpass filter for N=40');
subplot(212);
plot(n,abs(fftshift(fft(h))));
xlabel('n','fontsize',14);
ylabel('|h|','fontsize',14);
title('Ideal bandpass filter for N=40');
%% impulseresponse
clc, clear all, close all;
load impulseresponse.mat;
figure;
stem(h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Impulse response');
fvtool(h);
phasez(h);
%% FIR
clc, clear all, close all;
N=25;
n=-N:1:N;
x=0:1:(2*N);
w=pi/3;
M=(N-1)/2;
d=w/pi*sinc(w/pi*n);
D=fft(d);
G=D*exp(-1i*M*w);
g=ifft(G);
ham=hamming(length(n))';
h=ham.*g;
figure;
stem(x,h);
xlabel('n','fontsize',14);
ylabel('h','fontsize',14);
title('Impulse response');
fvtool(h);
phasez(h);
%% PM
clc, clear all, close all;
f=[0.15 0.175];
a=[1,0];
rp=[1.2589 0.00316];
fs=1;
[n,fo,mo,w]=firpmord(f,a,rp,fs);
b=firpm(n,fo,mo,w);
figure;
freqz(b);
figure;
impz(b);

%% Spectrograms
clc, clear all, close all;
load spectrogram.mat;
plot(abs(fft(x)));
%%
clc, clear all, close all;
wavread sound1.wav;
plot(20*log10(abs(fft(ans))));

%%
clc, clear all, close all;
wavread sound2.wav;
spectrogram(ans,'yaxis');